### ISSUE TITLE
Firefox Support?

### ISSUE THREAD

**Issue by Diom** [kzu/azdo#2]
Just a query on whether you are considering adding FF support at some point in the future?
Otherwise you could potentially add this as an azdo extension so you are not needing to support multiple browser extensions?

**Comment by kzu** [comment]
Luckily, with Edge now also aligned with Chrome, supporting multiple browsers is way easier now :). No idea about the FF extensibility model. This is an area where it would be great if someone could chime in with a contribution, I'm happy to take it and publish it!

**Comment by kzu** [comment]
Closing for now since there doesn't seem to be much traction and nobody volunteered. Plz feel free to reopen if the situation changes.
