### ISSUE TITLE
Linkinator: Workitems do not have org/project.

### ISSUE THREAD

**Issue by rjvdboon** [kzu/azdo#3]
I really like this extension, but in Chrome when I visit my own (non devdiv) org/project and have the linkinator create a link it will create the super short version (work.azdo.io/12345) instead of the org/project version work.azdo.io/org/project/12345.
Oh, please note that "resolved, won't fix" is also an answer! (I can use the url directly as well, the chrome extension is not required.)

https://github.com/kzu/azdo/blob/2b91b11fc327e22b51791297f89819405b348522/linkinator/background.js#L83-L89

**Comment by kzu** [comment]
ugh, that's a bug!

**Comment by kzu** [comment]
Now waiting for approval both on chrome devstore as well as the edge store ;)
