### ISSUE TITLE
feature suggestion: even shorter urls

### ISSUE THREAD

**Issue by iricigor** [kzu/azdo#5]
How about adding also even shorter versions of url, like this:
- b for builds
- r for releases
- w for wiki
- i for work items
- t for tasks

So, for example first line can be replaced also with a second line

`http://releases.azdo.io/{org}/{project}/{id}` 

`http://r.azdo.io/{org}/{project}/{id}`

**Comment by kzu** [comment]
Yeah, sounds good! I wonder if the browser extension should also switch to that by default
